version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      all-gradle:
        patterns:
          - "*"
    ignore:
      - dependency-name: "com.charleskorn.kaml:kaml"
      - dependency-name: "org.jetbrains.kotlinx:kotlinx-datetime"
      - dependency-name: "io.kotest"
      - dependency-name: "io.kotest:*"
