version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      all-gradle:
        patterns:
          - "*"
    ignore:
      # Updating will cause compatibility issues with Ktor.
      # We should wait for an update in Ktor.
      - dependency-name: "com.charleskorn.kaml:kaml"
      - dependency-name: "org.jetbrains.kotlinx:kotlinx-datetime"
      # Something up with the Kotest gradle plugin that causes this to break
      - dependency-name: "io.kotest"
      - dependency-name: "io.kotest:*"
