<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.acme</groupId>
    <artifactId>ktor-server-maven</artifactId>
    <version>0.0.1</version>
    <name>ktor-server-maven</name>
    <properties>
        <kotlin.code.style>official</kotlin.code.style>
        <kotlin_version>2.3.20-Beta2</kotlin_version>
        <logback_version>1.5.29</logback_version>
        
    </properties>
    <dependencies>
        <dependency>
            <groupId>null</groupId>
            <artifactId>null</artifactId>
            <version>null</version>
        </dependency>
        <dependency>
            <groupId>null</groupId>
            <artifactId>null</artifactId>
            <version>null</version>
        </dependency>
        <dependency>
            <groupId>null</groupId>
            <artifactId>null</artifactId>
            <version>null</version>
        </dependency>
        <dependency>
            <groupId>null</groupId>
            <artifactId>null</artifactId>
            <version>null</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback_version}</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-test</artifactId>
            <version>${kotlin_version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>null</groupId>
            <artifactId>null</artifactId>
            <version>null</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <sourceDirectory>${project.basedir}/src/main/kotlin</sourceDirectory>
        <testSourceDirectory>${project.basedir}/src/test/kotlin</testSourceDirectory>
        <resources>
            <resource>
                <directory>${project.basedir}/src/main/resources</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <artifactId>kotlin-maven-plugin</artifactId>
                <groupId>org.jetbrains.kotlin</groupId>
            </plugin>
        </plugins>
    </build>
</project>
