ktor:
  application:
    modules:
      - org.jetbrains.kastle.server.GeneratorKt.provideGenerator
      - org.jetbrains.kastle.server.JsonKt.json
      - org.jetbrains.kastle.server.RoutingKt.routing
      - org.jetbrains.kastle.server.SerializationKt.serialization
      - org.jetbrains.kastle.server.MonitoringKt.monitoring
      - org.jetbrains.kastle.server.ErrorHandlingKt.errorHandling
  deployment:
    port: 2626

repository:
  dir: export

# TODO not in use
mcp:
  implementation:
    name: kastle
    version: 0.1.0
  options:
    prompts:
      listChanged: true
    resources:
      subscribe: true
      listChanged: true
    tools:
      subscribe: true