# FUS Analytics Configuration
fus {
  productName = ${?FUS_PRODUCT_NAME}
  productCode = ${?FUS_PRODUCT_CODE}
  recorderCode = ${?FUS_RECORDER_CODE}

  recorderVersion = "1"
  recorderVersion = ${?FUS_RECORDER_VERSION}

  baselineVersion = "0"
  baselineVersion = ${?FUS_BASELINE_VERSION}

  buildNumber = "1.0"
  buildNumber = ${?FUS_BUILD_NUMBER}

  test = true
  test = ${?ANALYTICS_TEST_MODE}

  flushEventsDelaySeconds = 10
  flushEventsDelaySeconds = ${?ANALYTICS_FLUSH_DELAY_SECONDS}
}
