# Generate a project
POST http://localhost:8080/api/generate/download
Content-Type: application/json

{
  "name": "abrakadabra",
  "group": "wizards.rule",
  "properties": {
    "acme/properties/booleanProperty": true
  },
  "packs": [
    "com.acme/parent",
    "com.acme/child",
    "com.acme/properties"
  ]
}