[versions]
android-activity-compose = "1.7.2"


[libraries]
android-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "android-activity-compose" }


[plugins]
kotlin.multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version = "2.1.20" }

android.library = { id = "com.android.library", version = "8.5.2" }

kotlin.jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.1.20" }

jetbrains.compose = { id = "org.jetbrains.compose", version = "2.1.20" }

compose.compiler = { id = "org.jetbrains.kotlin.plugin.compose", version = "2.1.20" }

android.application = { id = "com.android.application", version = "8.5.2" }
